export const SET_FILE = "SET_FILE";
export const CREATE_FILE = "CREATE_FILE";
export const SET_PROGRESS = "SET_PROGRESS";
export const FILE_UPLOADED = "FILE_UPLOADED";
export const CLEAR_UPLOADS = "CLEAR_UPLOADS";
export const FILES_RECEIVED = "FILES_RECEIVED";
export const SET_TOTAL_FILES = "SET_TOTAL_FILES";
export const SET_PROPERTY_FILE = "SET_PROPERTY_FILE";
